# HAFTRAP Plotting Boxplots


## Set up
```{r}
# Import relevant libraries
library(tidyverse)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/HAFTRAP-summary")
```

```{r}
# Get file path
if (!endsWith(getwd(), "HAFTRAP-summary")) {
  stop("Incorrect working directory")
}
```

## Load cleaned data
Path to data
```{r}
# Set path to data
path_to_data <- "data_summarized/"
```

## Load Summary Data
```{r}
pm_raw <- read_csv(paste0(path_to_data, "summary_pm_raw.csv"))
ufp_raw <- read_csv(paste0(path_to_data, "summary_ufp_raw.csv"))
bc_raw <- read_csv(paste0(path_to_data, "summary_bc_raw.csv"))

pm_redu <- read_csv(paste0(path_to_data, "summary_pm_redu.csv"))
ufp_redu <- read_csv(paste0(path_to_data, "summary_ufp_redu.csv"))
bc_redu <- read_csv(paste0(path_to_data, "summary_bc_redu.csv"))
```


## Plotting for Indoor and Outdoor raw concentrations
Define lists for plot titles
```{r}
name_map <- c(pm1 = "PM 1 Concentration", pm25 = "PM 2.5 Concentration",
              pm10 = "PM 10 Concentration", pm1num = "PM 1 Particle Count",
              concent = "CPC Particle Count", 
              uv_bc1 = "Black Carbon (UV) Conc.")

pollutant_map <- c(pm1 = "PM 1", pm25 = "PM 2.5", pm10 = "PM 10", 
                   pm1num = "PM 1 Count", concent = "CPC Count", 
                   uv_bc1 = "Black Carbon")

environment_map <- c(indoor = "Indoor", outdoor = "Outdoor", 
                     ratio = "I/O Ratio")
```

```{r}
# For a given dataset of ratio data, specify the particle type
custom_boxplot <- function(df_raw, df_redu, pollutant, env) {
  
  # Get value of mean % reduction
  redu_val <- df_redu %>%
    filter(p_type == pollutant, environment == env,
           participant_id == "all") %>%
    select(mean) %>% as.numeric() %>% round(digits = 1)
  
  # Filter raw data to relevant pollutant and environment, recode case
  raw_stats <- df_raw %>%
    filter(p_type == pollutant, environment == env, 
           participant_id == "all") %>%
    mutate(case = recode_factor(case, "off" = "Sham", "on" = "HEPA"))
  
  # Set y position of mean annotation to the top of plot
  redu_y <- raw_stats %>% select(q95) %>% max()

  plot.new()
  
  new_plot <- raw_stats %>%
    # Plot filtered data
    ggplot(aes(x = case, fill = case)) +
      # Create boxplot with each situation (case + env)
      geom_boxplot(aes(ymin = q5, lower = q25, middle = median, 
                       upper = q75, ymax = q95), stat = "identity") +
      geom_point(aes(y = mean), shape = 15, color = "#0044C0") +
      # geom_text(aes(y = mean), label = "(mean)", hjust = 0, nudge_x = 0.02) +
      geom_label(x = 1.5, y = redu_y, fill = "#DDDDDD", vjust = "inward",
                label = paste0("Mean Reduction = ", redu_val, "%")) +
      # Set title
      labs(title = paste("Overall", pollutant_map[pollutant],
                         environment_map[env]),
           x = "Purifier Filter", y = name_map[pollutant]) +
      theme_light() +
      theme(legend.position = "none")
  
  plot(new_plot)
  legend("top", legend = c("Mean"), fill = c("#0044C0"), cex = 0.8)
}
```

## Plot indoor data boxplots
```{r}
# PM 2.5
pm_raw %>% custom_boxplot(pm_redu, "pm25", "indoor")
# PM 10
pm_raw %>% custom_boxplot(pm_redu, "pm10", "indoor")
# UFP
ufp_raw %>% custom_boxplot(ufp_redu, "concent", "indoor")
# Black Carbon
bc_raw %>% custom_boxplot(bc_redu, "uv_bc1", "indoor")
```


## Plot I/O Ratio data boxplots
```{r}
# PM 2.5
pm_raw %>% custom_boxplot(pm_redu, "pm25", "ratio")
# PM 10
pm_raw %>% custom_boxplot(pm_redu, "pm10", "ratio")
# UFP
ufp_raw %>% custom_boxplot(ufp_redu, "concent", "ratio")
# Black Carbon
bc_raw %>% custom_boxplot(bc_redu, "uv_bc1", "ratio")
```


