# HAFTRAP Saving Cleaned Data as CSVs
For hand-off, not to replace RData files in cleaned data. If running this script for the first time, create a folder called "clean_csv" in `other_scripts` (parent folder of this script).

## Set up
```{r}
# Import relevant libraries
library(tidyverse)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/HAFTRAP-summary")
```

```{r}
# Get file path
if (!endsWith(getwd(), "HAFTRAP-summary")) {
  stop("Incorrect working directory")
}
```

Path to data
```{r}
# Set path to data
path_to_data <- "data_cleaned/"
```

## Load data
```{r}
# Define column lists for each pollutant group
id_cols <- c("date", "participant_id", "environment", "case")
particulate_matter_cols <- c(id_cols, "pm1", "pm25", "pm10", "pm1num")
gas_phase_cols <- c(id_cols, "no", "co", "no2")

load(paste0(path_to_data, "cleaned_Olin_modpm.RData"))
modpm_olin <- modpm_df
load(paste0(path_to_data, "cleaned_Olin_modulair.RData"))
modulair_olin <- modulair_df
load(paste0(path_to_data, "cleaned_SCOPE_modulair.RData"))
modulair_scope <- modulair_df
load(paste0(path_to_data, "cleaned_Olin_cpc.RData"))
cpc_olin <- cpc_df
load(paste0(path_to_data, "cleaned_SCOPE_cpc.RData"))
cpc_scope <- cpc_df
load(paste0(path_to_data, "cleaned_Tufts_cpc.RData"))
cpc_tufts <- cpc_df
load(paste0(path_to_data, "cleaned_Olin_aethalometer.RData"))
bc_all <- aethalometer_df

# Combine all Modulair data
modulair_all <- rbind(modulair_olin, modulair_scope)

# Combine all particulate matter data
pm_all <- modulair_all %>% 
  select(all_of(particulate_matter_cols)) %>%
  rbind(modpm_olin)

# Combine Brechtel CPC data
ufp_brechtel <- rbind(cpc_olin, cpc_scope)
ufp_all <- rbind(ufp_brechtel, cpc_tufts)

# Combine all Modulair data
gp_all <- modulair_olin %>%
  rbind(modulair_scope) %>%
  select(all_of(gas_phase_cols))
```

# Save data as CSVs
```{r}
write_csv(pm_all, "other_scripts/clean_csv/clean_pm.csv")
write_csv(ufp_all, "other_scripts/clean_csv/clean_ufp.csv")
write_csv(gp_all, "other_scripts/clean_csv/clean_gp.csv")
write_csv(bc_all, "other_scripts/clean_csv/clean_bc.csv")
```

