# HAFTRAP Plotting Diurnals


## Set up
```{r}
# Import relevant libraries
library(tidyverse)
library(openair)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/HAFTRAP-summary")
```

```{r}
# Get file path
if (!endsWith(getwd(), "HAFTRAP-summary")) {
  stop("Incorrect working directory")
}
```

Path to data
```{r}
# Set path to data
path_to_data <- "data_cleaned/"
```

## Load data
```{r}
# Define column lists for each pollutant group
id_cols <- c("date", "participant_id", "environment", "case")
particulate_matter_cols <- c(id_cols, "pm1", "pm25", "pm10", "pm1num")

load(paste0(path_to_data, "cleaned_Olin_modpm.RData"))
modpm_olin <- modpm_df
load(paste0(path_to_data, "cleaned_Olin_modulair.RData"))
modulair_olin <- modulair_df
load(paste0(path_to_data, "cleaned_SCOPE_modulair.RData"))
modulair_scope <- modulair_df
load(paste0(path_to_data, "cleaned_Olin_cpc.RData"))
cpc_olin <- cpc_df
load(paste0(path_to_data, "cleaned_SCOPE_cpc.RData"))
cpc_scope <- cpc_df
load(paste0(path_to_data, "cleaned_Tufts_cpc.RData"))
cpc_tufts <- cpc_df
load(paste0(path_to_data, "cleaned_Olin_aethalometer.RData"))
olin_aeth <- aethalometer_df

# Combine all Modulair data
modulair_all <- rbind(modulair_olin, modulair_scope)

# Combine all particulate matter data
particulate_matter <- modulair_all %>% 
  select(all_of(particulate_matter_cols)) %>%
  rbind(modpm_olin)

# Combine Brechtel CPC data
ufp_brechtel <- rbind(cpc_olin, cpc_scope)
ufp_all <- rbind(ufp_brechtel, cpc_tufts)
```

```{r}
pm_plot <- particulate_matter %>%
  filter(environment == "indoor") %>%
  mutate(case = recode_factor(case, "off" = "Sham", "on" = "HEPA")) %>%
  timeVariation(pollutant = "pm25", ylab = "pm25 (ug/m3)", group = "case",
                local.tz = "America/New_York", plot = FALSE)
```
```{r}
pm_subplot <- pm_plot$plot$hour

plot.new()
plot(pm_subplot)

title(main = expression("Mean Diurnal Indoor PM"[2.5]), line = 3)
legend("topleft", inset = 0.05, legend = c("Sham", "HEPA"), 
       title = "Purifier type", fill = c("#F8766D", "#00BFC4"))
```

```{r}
ufp_plot <- ufp_all %>%
  filter(environment == "indoor") %>%
  mutate(case = recode_factor(case, "off" = "Sham", "on" = "HEPA")) %>%
  timeVariation(pollutant = "concent", 
                ylab = "UFP Concentration (particles/cc)", 
                group = "case", local.tz = "America/New_York", plot = FALSE)
```

```{r}
ufp_subplot <- ufp_plot$plot$hour

plot.new()
plot(ufp_subplot)

title(main = expression("Mean Diurnal Indoor UFP Count"), line = 3)
legend("topleft", inset = 0.05, legend = c("Sham", "HEPA"), 
       title = "Purifier type", fill = c("#F8766D", "#00BFC4"))
```




```{r}
bc_plot <- olin_aeth %>%
  filter(environment == "indoor") %>%
  mutate(case = recode_factor(case, "off" = "Sham", "on" = "HEPA")) %>%
  timeVariation(pollutant = "uv_bc1", ylab = "BC Conc. (ng/m3)", 
                group = "case", local.tz = "America/New_York", plot = FALSE)
```

```{r}
bc_subplot <- bc_plot$plot$hour

plot.new()
plot(bc_subplot)

title(main = expression("Mean Diurnal Indoor Black Carbon (UV)"), line = 3)
legend("topleft", inset = 0.05, legend = c("Sham", "HEPA"), 
       title = "Purifier type", fill = c("#F8766D", "#00BFC4"))
```


