# CPC Data Cleaning
This file cleans the CPC Data for Tufts deployments

## Load Libraries
```{r}
library(tidyverse)
library(data.table)
library(readxl)
```

Set working directory
```{r, setup, include=FALSE}
working_dir <- "HAFTRAP-summary"
knitr::opts_knit$set(root.dir = paste0("~/", working_dir))
```

Check for working directory
```{r}
# Check file path
if (!endsWith(getwd(), working_dir)) {
  stop("Incorrect working directory")
}
```

## Read data
```{r}
path_to_data <- "data_raw/Tufts/cpc/"
```

```{r}
# List all raw CPC data files in Tufts data, filtering out irrelevant files
cpc_files <- list.files(path = path_to_data, recursive = TRUE)
cpc_files <- grep("xlsx|txt", cpc_files, value = TRUE, invert = TRUE)
```

```{r}
# Read all CPC files - this takes a while (~ 5 min on my PC)
all_df <- data.frame()

for (cpc_file in cpc_files) {
  # File path
  file_path = paste0(path_to_data, cpc_file)
  
  # Get file metadata
  file_info <- file.info(file_path)
  
  # Skip empty files
  if(file_info$size > 500) {
    cpc_file_parts <- str_split_1(cpc_file, "/")
    
    # Get participant ID
    participant_parts <- str_split_1(cpc_file_parts[1], " ")
    participant <- as.integer(participant_parts[3])
    
    # Get environment  
    env_period_str <- str_to_lower(cpc_file_parts[2])
    
    env <- NA
    if (grepl("in", env_period_str)) {
      env <- "indoor"
    } else if (grepl("out", env_period_str)){
      env <- "outdoor"
    }
    
    # Get period, default is 1
    per <- 1
    if (grepl("2", env_period_str)) {
      per <- 2
    }
    
    # Read file into dataframe
    df <- fread(file_path, header = TRUE, skip = 5) %>%
      # Merge the date and time column
      unite(col = "date", "Date", "Time", sep = " ") %>%
      # Convert to datetime object and insert environment, participant ID
      mutate(date = as.POSIXct(date, format = "%Y/%m/%d %H:%M:%S", 
                               tz = "America/New_York"),
             environment = env, participant_id = participant, period = per)

    # Combine with overall dataframe
    all_df <- rbind(all_df, df)
    
    print(paste("Read", cpc_file))
  }
}
```
